import type { Metadata } from "next";
import { Inria_Serif } from "next/font/google";
import "./globals.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import { Navbar } from "@/components/navbar";
import { theme } from "@/lib/theme";
import "@mantine/notifications/styles.css";
import { cookies } from "next/headers";
import { Notifications } from "@mantine/notifications";
const font = Inria_Serif({ weight: ["300", "400", "700"], preload: false });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = cookies();
  let token = cookie.get("token");
  return (
    <html lang="en" className={font.className}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className="px-5 py-4">
        <MantineProvider theme={theme}>
          <Notifications />
          <Navbar token={token?.value} />
          <div className="h-[71px]"></div>

          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
