import type { Metadata } from "next";
import { Inria_Serif } from "next/font/google";
import "./globals.css";
import "@mantine/dates/styles.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import { Navbar } from "@/components/navbar";
import { theme } from "@/lib/theme";
import "@mantine/notifications/styles.css";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import { cookies } from "next/headers";
import { Notifications } from "@mantine/notifications";
import { DatesProvider } from "@mantine/dates";
const font = Inria_Serif({ weight: ["300", "400", "700"], preload: false });
import "dayjs/locale/ru";
export const metadata: Metadata = {
  title: "FreeFlex",
  icons: [
    {
      rel: "icon",
      type: "image/svg",
      sizes: "100x150",
      url: "/assets/images/svgs/logo_mini.svg",
    },
  ],
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = cookies();
  let token = cookie.get("token");
  return (
    <html lang="en" className={font.className}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme}>
          <Notifications />
          <Navbar token={token?.value} />
          <div className="h-[88px]"></div>

          <DatesProvider
            settings={{
              locale: "ru",
              consistentWeeks: true,
            }}
          >
            {children}
          </DatesProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
